name = "expense-tracker-api"
main = "src/index.ts"
compatibility_date = "2024-09-28"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "EXPENSE_KV"
id = "ff9777d0184e4f93b8b91be2d56ea575"
