name: Deploy Frontend to Firebase

on:
  push:
    branches: [ main ]
    paths: [ 'web/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'web/**' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        
    - name: Enable Corepack
      run: corepack enable
        
    - name: Install dependencies
      run: |
        cd web
        pnpm install --frozen-lockfile
        
    - name: Run tests
      run: |
        cd web
        pnpm run test
        pnpm run type-check
        pnpm run lint
        
    - name: Build
      run: |
        cd web
        pnpm run build
        
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: opefyre-expense-tracker
        target: expenfyre
        channelId: live
