name: Deploy Backend to Cloudflare

on:
  push:
    branches: [ main ]
    paths: [ 'api/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'api/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Install dependencies
      run: |
        cd api
        pnpm install
      env:
        PATH: ${{ env.PATH }}:${{ env.HOME }}/.local/share/pnpm
        
    - name: Run tests
      run: |
        cd api
        pnpm run test
        pnpm run type-check
        pnpm run lint
      env:
        PATH: ${{ env.PATH }}:${{ env.HOME }}/.local/share/pnpm
        
    - name: Deploy to Cloudflare
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: deploy
        workingDirectory: api
