name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd web
        npm install
        
    - name: Run TypeScript type checking
      run: |
        cd web
        npm run type-check
        
    - name: Run ESLint
      run: |
        cd web
        npm run lint
        
    - name: Run unit tests
      run: |
        cd web
        npm run test
        
    - name: Run component tests
      run: |
        cd web
        npm run test:components
        
    - name: Run integration tests
      run: |
        cd web
        npm run test:integration
        
    - name: Run E2E tests
      run: |
        cd web
        npm run test:e2e

  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd api
        npm install
        
    - name: Run TypeScript type checking
      run: |
        cd api
        npm run type-check
        
    - name: Run ESLint
      run: |
        cd api
        npm run lint
        
    - name: Run unit tests
      run: |
        cd api
        npm run test
        
    - name: Run API tests
      run: |
        cd api
        npm run test:api

  test-integration:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Run full integration tests
      run: |
        npm run test:integration:full
      env:
        TEST_API_URL: https://expense-tracker-api.opefyre.workers.dev
        TEST_FRONTEND_URL: https://expenfyre.web.app
